// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs5mIdvB3p404gvcaqDpAVRS3LqqSXwl8',
    appId: '1:999520997842:web:9689a2e4db211c1045380b',
    messagingSenderId: '999520997842',
    projectId: 'television-36454',
    authDomain: 'television-36454.firebaseapp.com',
    storageBucket: 'television-36454.appspot.com',
    measurementId: 'G-1T15017SGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCc5YO_weTunJ-el_aWeNSWjG6fyuBKms',
    appId: '1:999520997842:android:4035aba3ad0a735245380b',
    messagingSenderId: '999520997842',
    projectId: 'television-36454',
    storageBucket: 'television-36454.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMiV0FpQrb1pZ-rG3-8_EdInFyJLMCgBI',
    appId: '1:999520997842:ios:6d6ef1dafe41c98e45380b',
    messagingSenderId: '999520997842',
    projectId: 'television-36454',
    storageBucket: 'television-36454.appspot.com',
    iosBundleId: 'com.example.ourMusic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMiV0FpQrb1pZ-rG3-8_EdInFyJLMCgBI',
    appId: '1:999520997842:ios:1ebdd0038d20a94a45380b',
    messagingSenderId: '999520997842',
    projectId: 'television-36454',
    storageBucket: 'television-36454.appspot.com',
    iosBundleId: 'com.example.ourMusic.RunnerTests',
  );
}
